#!/usr/bin/env bash

#-------------------------------------------------------------------------
#  Catrina's Additional Setup After Installing Using DMS Installer
#-------------------------------------------------------------------------

echo
echo "Refreshing Repo's"
echo

sudo pacman -Syu --noconfirm

#-------------------------------------------------------------------------

echo
echo "Done!"
echo

echo
echo "Add Missing Stuff For Niri"
echo

PKGS=(
        'xdg-desktop-portal-gnome'
        'gnome-keyring'
        'wlr-randr'
        'cava'
)

for PKG in "${PKGS[@]}"; do
    echo "INSTALLING: ${PKG}"
    sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

#-------------------------------------------------------------------------

echo
echo "Install Theme Support"
echo

pacman -S --noconfirm \
  adw-gtk-theme \
  nwg-look

PKGS=(
        'adw-gtk-theme'
        'nwg-look'
)

for PKG in "${PKGS[@]}"; do
    echo "INSTALLING: ${PKG}"
    sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

#-------------------------------------------------------------------------

echo
echo "Install Core App's. GTK Core Cause Niri Loves It and I'm Lazy"
echo

PKGS=(
        'nautilus'
        'loupe'
        'decibels'
        'showtime'
        'papers'
        'gnome-text-editor'
)

for PKG in "${PKGS[@]}"; do
    echo "INSTALLING: ${PKG}"
    sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

#-------------------------------------------------------------------------

echo
echo "Install Misc System App's"
echo

PKGS=(
        'lact'
        'flatpak'
)

for PKG in "${PKGS[@]}"; do
    echo "INSTALLING: ${PKG}"
    sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo
