#!/usr/bin/env bash

#-------------------------------------------------------------------------
#  Catrina's AUR Packages Installer
#-------------------------------------------------------------------------

echo
echo "Installing Aur Packages. Skull Emoji"
echo

paru -S --noconfirm qt6ct-kde
paru -S --noconfirm bazaar

echo
echo "Done!"
echo
