#!/usr/bin/env bash

#-------------------------------------------------------------------------
#  Catrina's Additional Setup After Installing Using DMS Installer
#-------------------------------------------------------------------------

# To Do:
# Double Check Packages and Add More If Needed
# Make This File Executable
# Test On VM

#-------------------------------------------------------------------------

echo
echo "Refreshing Repo's"
echo

sudo pacman -Syu --noconfirm

#-------------------------------------------------------------------------

echo
echo "Done!"
echo

echo
echo "Add Missing Stuff For Niri"
echo

PKGS=(
        'xdg-desktop-portal-gnome'
        'gnome-keyring'
        'wlr-randr'
        'cava'
)

for PKG in "${PKGS[@]}"; do
    echo "INSTALLING: ${PKG}"
    sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

#-------------------------------------------------------------------------

echo
echo "Install Theme Support"
echo

pacman -S --noconfirm \
  adw-gtk-theme \
  nwg-look

PKGS=(
        'adw-gtk-theme'
        'nwg-look'
)

for PKG in "${PKGS[@]}"; do
    echo "INSTALLING: ${PKG}"
    sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

#-------------------------------------------------------------------------

echo
echo "Install Core App's. GTK Core Cause Niri Loves It and I'm Lazy"
echo

PKGS=(
        'nautilus'
        'loupe'
        'decibels'
        'showtime'
        'papers'
        'gnome-text-editor'
)

for PKG in "${PKGS[@]}"; do
    echo "INSTALLING: ${PKG}"
    sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

#-------------------------------------------------------------------------

echo
echo "Install Misc System App's"
echo

PKGS=(
        'lact'
        'flatpak'
)

for PKG in "${PKGS[@]}"; do
    echo "INSTALLING: ${PKG}"
    sudo pacman -S "$PKG" --noconfirm
done

echo
echo "Done!"
echo

#-------------------------------------------------------------------------

echo
echo "Install Stuff From The AUR. Skull Emoji"
echo

cd "${HOME}"

echo "CLONING: AURIC"
git clone "https://github.com/kitkat6464/AURIC.git"

PKGS=(
        'qt6ct-kde'
        'bazaar'
)

cd ${HOME}/AURIC
chmod +x auric.sh

for PKG in "${PKGS[@]}"; do
    ./auric.sh -i $PKG
done

echo
echo "Done!"
echo
