#!/usr/bin/env bash

#-------------------------------------------------------------------------
#  Catrina's AUR Packages Installer
#-------------------------------------------------------------------------

echo
echo "Installing Aur Packages. Skull Emoji"
echo

paru -S -y qt6ct-kde
paru -S -y bazaar

echo
echo "Done!"
echo
